// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(StoreContext))]
    partial class StoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PriceUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityInStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "brand1",
                            Description = "description1",
                            Name = "name1",
                            Price = 10L,
                            PriceUrl = "url1",
                            QuantityInStock = 5,
                            Type = "type1"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "brand2",
                            Description = "description2",
                            Name = "name2",
                            Price = 12L,
                            PriceUrl = "url2",
                            QuantityInStock = 2,
                            Type = "type2"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "brand3",
                            Description = "description3",
                            Name = "name3",
                            Price = 13L,
                            PriceUrl = "url3",
                            QuantityInStock = 3,
                            Type = "type3"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "brand4",
                            Description = "description4",
                            Name = "name4",
                            Price = 14L,
                            PriceUrl = "url4",
                            QuantityInStock = 4,
                            Type = "type4"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "brand5",
                            Description = "description5",
                            Name = "name5",
                            Price = 15L,
                            PriceUrl = "url5",
                            QuantityInStock = 5,
                            Type = "type5"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "brand6",
                            Description = "description6",
                            Name = "name6",
                            Price = 16L,
                            PriceUrl = "url6",
                            QuantityInStock = 6,
                            Type = "type6"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "brand7",
                            Description = "description7",
                            Name = "name7",
                            Price = 17L,
                            PriceUrl = "url7",
                            QuantityInStock = 7,
                            Type = "type7"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "brand8",
                            Description = "description8",
                            Name = "name8",
                            Price = 18L,
                            PriceUrl = "url8",
                            QuantityInStock = 8,
                            Type = "type8"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "brand9",
                            Description = "description9",
                            Name = "name9",
                            Price = 19L,
                            PriceUrl = "url9",
                            QuantityInStock = 9,
                            Type = "type9"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
